build

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -29,8 +29,8 @@ before_install:
   - export DOWNLOADS_CACHE_DIR="$HOME/.build-downloads"
 
   # Remove mysql
-  - sudo apt-get purge -y mysql-server mysql-client mysql-common mysql-server-core-* mysql-client-core-*
-  - sudo rm -rf /etc/mysql /var/lib/mysql
+#  - sudo apt-get purge -y mysql-server mysql-client mysql-common mysql-server-core-* mysql-client-core-*
+#  - sudo rm -rf /etc/mysql /var/lib/mysql
 
   # Loading apt cache
   - |
@@ -49,34 +49,34 @@ before_install:
   #   https://www.percona.com/doc/percona-server/8.0/installation/apt_repo.html
   #   https://www.percona.com/doc/percona-server/8.0/myrocks/install.html
   # Fetch the repository packages from Percona web
-  - curl -L -o ./percona-release_latest_all.deb https://repo.percona.com/apt/percona-release_latest.$(lsb_release -sc)_all.deb
+#  - curl -L -o ./percona-release_latest_all.deb https://repo.percona.com/apt/percona-release_latest.$(lsb_release -sc)_all.deb
   # Install the downloaded package with dpkg. To do that, run the following commands as root or with sudo
-  - sudo dpkg -i ./percona-release_latest_all.deb
+#  - sudo dpkg -i ./percona-release_latest_all.deb
   # Enable the repository
-  - sudo percona-release setup ps80
+#  - sudo percona-release setup ps80
   # Install the server package
-  - sudo apt-get install -y percona-server-rocksdb
+#  - sudo apt-get install -y percona-server-rocksdb
   # View *.cnf
-  - cat /etc/mysql/conf.d/mysql.cnf
-  - cat /etc/mysql/mysql.conf.d/mysqld.cnf
+#  - cat /etc/mysql/conf.d/mysql.cnf
+#  - cat /etc/mysql/mysql.conf.d/mysqld.cnf
   # Starting the service
-  - sudo service mysql start
+#  - sudo service mysql start
   # Percona Server is distributed with several useful UDF (User Defined Function) from Percona Toolkit.
   #   See http://www.percona.com/doc/percona-server/8.0/management/udf_percona_toolkit.html for more details
-  - sudo mysql -e "CREATE FUNCTION fnv1a_64 RETURNS INTEGER SONAME 'libfnv1a_udf.so'"
-  - sudo mysql -e "CREATE FUNCTION fnv_64 RETURNS INTEGER SONAME 'libfnv_udf.so'"
-  - sudo mysql -e "CREATE FUNCTION murmur_hash RETURNS INTEGER SONAME 'libmurmur_udf.so'"
+#  - sudo mysql -e "CREATE FUNCTION fnv1a_64 RETURNS INTEGER SONAME 'libfnv1a_udf.so'"
+#  - sudo mysql -e "CREATE FUNCTION fnv_64 RETURNS INTEGER SONAME 'libfnv_udf.so'"
+#  - sudo mysql -e "CREATE FUNCTION murmur_hash RETURNS INTEGER SONAME 'libmurmur_udf.so'"
   # Enable the RocksDB storage engine in Percona Server
-  - sudo ps-admin --enable-rocksdb -u root
+#  - sudo ps-admin --enable-rocksdb -u root
   # View result
-  - sudo mysql -e "SHOW ENGINES"
-  - sudo mysql -e "SHOW VARIABLES"
+#  - sudo mysql -e "SHOW ENGINES"
+#  - sudo mysql -e "SHOW VARIABLES"
   # Create database
-  - sudo mysql -e "CREATE DATABASE gamedevby"
+#  - sudo mysql -e "CREATE DATABASE gamedevby"
   # Create user
-  - sudo mysql -e "CREATE USER 'gamedevby'@'localhost' IDENTIFIED BY 'gamedevby'"
-  - sudo mysql -e "GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES ON gamedevby.* TO 'gamedevby'@'localhost'"
-  - sudo mysql -e "FLUSH PRIVILEGES"
+#  - sudo mysql -e "CREATE USER 'gamedevby'@'localhost' IDENTIFIED BY 'gamedevby'"
+#  - sudo mysql -e "GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES ON gamedevby.* TO 'gamedevby'@'localhost'"
+#  - sudo mysql -e "FLUSH PRIVILEGES"
 
   # Install php 7.3
   - sudo apt-get install -y php7.3 php7.3-common php7.3-cli
@@ -88,37 +88,37 @@ before_install:
   - echo $PHP_EXTENSIONS_PATH
   - export PHP_VERSION=$(php -version | grep -P '(?<=PHP )([0-9]+\.[0-9]+\.[0-9]+[^ \n\t]*)' -o | grep -P '^[0-9]([^ \n\t]*)' -o)
   - echo $PHP_VERSION
-  - export PHP_AST_EXT_FILE="php-ast-$PHP_VERSION.so"
-  - export PHP_AST_EXT_PATH="$DOWNLOADS_CACHE_DIR/php-ast-release/$PHP_AST_EXT_FILE"
-  - |
-    if [ ! -f "$PHP_AST_EXT_PATH" ]; then
-      rm -rf $DOWNLOADS_CACHE_DIR/php-ast-release
-      mkdir -p $DOWNLOADS_CACHE_DIR/php-ast-release
-      mkdir -p $DOWNLOADS_CACHE_DIR/build
-      git clone -b 'v1.0.0' --single-branch --depth 1 https://github.com/nikic/php-ast.git $DOWNLOADS_CACHE_DIR/php-ast
-      export CFLAGS="-O3"
-      pushd $DOWNLOADS_CACHE_DIR/php-ast
-      phpize
-      ./configure
-      make
-      make test
-      mv modules/ast.so "$PHP_AST_EXT_PATH"
-      rm -rf $DOWNLOADS_CACHE_DIR/php-ast $DOWNLOADS_CACHE_DIR/build
-      popd
-    fi
-  - sudo cp -v -p $PHP_AST_EXT_PATH $PHP_EXTENSIONS_PATH/$PHP_AST_EXT_FILE
-  - echo "extension=$PHP_AST_EXT_FILE" | sudo tee --append /etc/php/7.3/cli/conf.d/20-ast.ini
-  - php -r 'function_exists("ast\parse_code") || (print("Failed to enable php-ast\n") && exit(1));'
+#  - export PHP_AST_EXT_FILE="php-ast-$PHP_VERSION.so"
+#  - export PHP_AST_EXT_PATH="$DOWNLOADS_CACHE_DIR/php-ast-release/$PHP_AST_EXT_FILE"
+#  - |
+#    if [ ! -f "$PHP_AST_EXT_PATH" ]; then
+#      rm -rf $DOWNLOADS_CACHE_DIR/php-ast-release
+#      mkdir -p $DOWNLOADS_CACHE_DIR/php-ast-release
+#      mkdir -p $DOWNLOADS_CACHE_DIR/build
+#      git clone -b 'v1.0.0' --single-branch --depth 1 https://github.com/nikic/php-ast.git $DOWNLOADS_CACHE_DIR/php-ast
+#      export CFLAGS="-O3"
+#      pushd $DOWNLOADS_CACHE_DIR/php-ast
+#      phpize
+#      ./configure
+#      make
+#      make test
+#      mv modules/ast.so "$PHP_AST_EXT_PATH"
+#      rm -rf $DOWNLOADS_CACHE_DIR/php-ast $DOWNLOADS_CACHE_DIR/build
+#      popd
+#    fi
+#  - sudo cp -v -p $PHP_AST_EXT_PATH $PHP_EXTENSIONS_PATH/$PHP_AST_EXT_FILE
+#  - echo "extension=$PHP_AST_EXT_FILE" | sudo tee --append /etc/php/7.3/cli/conf.d/20-ast.ini
+#  - php -r 'function_exists("ast\parse_code") || (print("Failed to enable php-ast\n") && exit(1));'
 
   # Build ICU
   - export ICU_VERSION="63.1"
   - export ICU_PREFIX="/opt/icu$ICU_VERSION"
-  - export ICU_BUILD_PATH="$DOWNLOADS_CACHE_DIR/icu/icu-$ICU_VERSION/icu/source"
+  - export ICU_BUILD_PATH="$DOWNLOADS_CACHE_DIR/icu/icu-$ICU_VERSION"
   - |
     if [ ! -d "$ICU_BUILD_PATH" ]; then
       rm -rf $DOWNLOADS_CACHE_DIR/icu
-      mkdir -p $DOWNLOADS_CACHE_DIR/icu/icu-$ICU_VERSION
-      pushd $DOWNLOADS_CACHE_DIR/icu/icu-$ICU_VERSION
+      mkdir -p $ICU_BUILD_PATH
+      pushd $ICU_BUILD_PATH
       ICU_VERSION_S=$(echo $ICU_VERSION | sed 's/\./-/g')
       echo -e "\n> git clone -b 'release-$ICU_VERSION_S' --single-branch --depth 1 https://github.com/nikic/php-ast.git ."
       git clone -b "release-$ICU_VERSION_S" --single-branch --depth 1 https://github.com/unicode-org/icu.git .
@@ -131,68 +131,68 @@ before_install:
       make test
       popd
     fi
-  - pushd $DOWNLOADS_CACHE_DIR/icu/icu-$ICU_VERSION/icu4c/source
+  - pushd $ICU_BUILD_PATH/icu4c/source
   # - sudo make install
-  - sudo make VERBOSE=1 V=1 AM_DEFAULT_VERBOSITY=1 --debug=j check-installed-icu
+#  - sudo make VERBOSE=1 V=1 AM_DEFAULT_VERBOSITY=1 --debug=j check-installed-icu
   - popd
 
   # Build intl ext
-  - export PHP_INTL_EXT_FILE="php-intl-$PHP_VERSION.so"
-  - export PHP_INTL_EXT_PATH="$DOWNLOADS_CACHE_DIR/php-intl-release/$PHP_INTL_EXT_FILE"
-  - |
-    if [ ! -f "$PHP_INTL_EXT_PATH" ]; then
-      rm -rf $DOWNLOADS_CACHE_DIR/php-intl-release
-      mkdir -p $DOWNLOADS_CACHE_DIR/php-intl-release
-      mkdir -p $DOWNLOADS_CACHE_DIR/build
-      mkdir -p $DOWNLOADS_CACHE_DIR/php-src
-      pushd $DOWNLOADS_CACHE_DIR/php-src
-      PHP_SHORT_VERSION=$(echo $PHP_VERSION | grep -P '^[0-9]+\.[0-9]+\.[0-9]+' -o)
-      echo -e "\n> git clone -b 'php-$PHP_SHORT_VERSION' --single-branch --depth 1 https://github.com/php/php-src.git ./php-$PHP_SHORT_VERSION"
-      git clone -b 'php-$PHP_SHORT_VERSION' --single-branch --depth 1 https://github.com/php/php-src.git ./php-$PHP_SHORT_VERSION
-      cd ./php-$PHP_SHORT_VERSION/ext/intl
-      export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ICU_PREFIX/lib
-      export TEST_PHP_ARGS="-q"
-      export CFLAGS="-O3"
-      export CXXFLAGS=$($ICU_PREFIX/bin/icu-config --cxxflags)
-      export CPPFLAGS
-      echo -e "\n> phpize"
-      phpize
-      echo -e "\n> ./configure --enable-intl --with-icu-dir=$ICU_PREFIX"
-      ./configure --enable-intl --with-icu-dir="$ICU_PREFIX"
-      echo -e "\n> make CXXFLAGS=$CXXFLAGS"
-      make CXXFLAGS=$CXXFLAGS
-      echo -e "\n> make test"
-      make test
-      rm -rf $DOWNLOADS_CACHE_DIR/php-src $DOWNLOADS_CACHE_DIR/build
-      popd
-    fi
-  - sudo cp -v -p $PHP_INTL_EXT_PATH $PHP_EXTENSIONS_PATH/$PHP_INTL_EXT_FILE
-  - echo "extension=$PHP_INTL_EXT_FILE" | sudo tee --append /etc/php/7.3/cli/conf.d/20-intl.ini
-  - php -r 'function_exists("intl_error_name") || (print("Failed to enable php-intl\n") && exit(1));'
+#  - export PHP_INTL_EXT_FILE="php-intl-$PHP_VERSION.so"
+#  - export PHP_INTL_EXT_PATH="$DOWNLOADS_CACHE_DIR/php-intl-release/$PHP_INTL_EXT_FILE"
+#  - |
+#    if [ ! -f "$PHP_INTL_EXT_PATH" ]; then
+#      rm -rf $DOWNLOADS_CACHE_DIR/php-intl-release
+#      mkdir -p $DOWNLOADS_CACHE_DIR/php-intl-release
+#      mkdir -p $DOWNLOADS_CACHE_DIR/build
+#      mkdir -p $DOWNLOADS_CACHE_DIR/php-src
+#      pushd $DOWNLOADS_CACHE_DIR/php-src
+#      PHP_SHORT_VERSION=$(echo $PHP_VERSION | grep -P '^[0-9]+\.[0-9]+\.[0-9]+' -o)
+#      echo -e "\n> git clone -b 'php-$PHP_SHORT_VERSION' --single-branch --depth 1 https://github.com/php/php-src.git ./php-$PHP_SHORT_VERSION"
+#      git clone -b 'php-$PHP_SHORT_VERSION' --single-branch --depth 1 https://github.com/php/php-src.git ./php-$PHP_SHORT_VERSION
+#      cd ./php-$PHP_SHORT_VERSION/ext/intl
+#      export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ICU_PREFIX/lib
+#      export TEST_PHP_ARGS="-q"
+#      export CFLAGS="-O3"
+#      export CXXFLAGS=$($ICU_PREFIX/bin/icu-config --cxxflags)
+#      export CPPFLAGS
+#      echo -e "\n> phpize"
+#      phpize
+#      echo -e "\n> ./configure --enable-intl --with-icu-dir=$ICU_PREFIX"
+#      ./configure --enable-intl --with-icu-dir="$ICU_PREFIX"
+#      echo -e "\n> make CXXFLAGS=$CXXFLAGS"
+#      make CXXFLAGS=$CXXFLAGS
+#      echo -e "\n> make test"
+#      make test
+#      rm -rf $DOWNLOADS_CACHE_DIR/php-src $DOWNLOADS_CACHE_DIR/build
+#      popd
+#    fi
+#  - sudo cp -v -p $PHP_INTL_EXT_PATH $PHP_EXTENSIONS_PATH/$PHP_INTL_EXT_FILE
+#  - echo "extension=$PHP_INTL_EXT_FILE" | sudo tee --append /etc/php/7.3/cli/conf.d/20-intl.ini
+#  - php -r 'function_exists("intl_error_name") || (print("Failed to enable php-intl\n") && exit(1));'
 
   # View php detailed info
   - ls -la $PHP_EXTENSIONS_PATH
   - sudo php -i
 
   # Install composer
-  - |
-    if [ ! -f "$DOWNLOADS_CACHE_DIR/composer-setup.php" ]; then
-      curl -L -o $DOWNLOADS_CACHE_DIR/composer-setup.php https://getcomposer.org/installer
-    fi
-  - sudo php $DOWNLOADS_CACHE_DIR/composer-setup.php --install-dir=/usr/local/bin --filename=composer
-  - composer diagnose --no-interaction --ansi --verbose
-  - sudo mkdir -p ~/.composer/
-  - sudo chown -R $USER ~/.composer/
-  - composer --no-progress --no-interaction --no-ansi global require hirak/prestissimo
+#  - |
+#    if [ ! -f "$DOWNLOADS_CACHE_DIR/composer-setup.php" ]; then
+#      curl -L -o $DOWNLOADS_CACHE_DIR/composer-setup.php https://getcomposer.org/installer
+#    fi
+#  - sudo php $DOWNLOADS_CACHE_DIR/composer-setup.php --install-dir=/usr/local/bin --filename=composer
+#  - composer diagnose --no-interaction --ansi --verbose
+#  - sudo mkdir -p ~/.composer/
+#  - sudo chown -R $USER ~/.composer/
+#  - composer --no-progress --no-interaction --no-ansi global require hirak/prestissimo
 
   # Install symfony cli https://symfony.com/download
-  - |
-    if [ ! -f "$DOWNLOADS_CACHE_DIR/symfony-setup" ]; then
-      curl -L -o $DOWNLOADS_CACHE_DIR/symfony-setup https://get.symfony.com/cli/installer
-    fi
-  - sudo bash $DOWNLOADS_CACHE_DIR/symfony-setup
-  - sudo mv ~/.symfony/bin/symfony /usr/local/bin/symfony
-  - sudo symfony -V
+#  - |
+#    if [ ! -f "$DOWNLOADS_CACHE_DIR/symfony-setup" ]; then
+#      curl -L -o $DOWNLOADS_CACHE_DIR/symfony-setup https://get.symfony.com/cli/installer
+#    fi
+#  - sudo bash $DOWNLOADS_CACHE_DIR/symfony-setup
+#  - sudo mv ~/.symfony/bin/symfony /usr/local/bin/symfony
+#  - sudo symfony -V
 
   # Updating apt cache
   - echo "Start updating apt cache"
@@ -202,26 +202,26 @@ before_install:
 
 install:
   # Validation
-  - composer validate --strict --no-interaction --ansi --verbose
-  - sudo symfony security:check
+#  - composer validate --strict --no-interaction --ansi --verbose
+#  - sudo symfony security:check
 
   # Install Composer dependencies
-  - composer --verbose --prefer-dist --no-progress --no-interaction --ansi --classmap-authoritative install
-  - composer licenses --no-interaction --ansi --verbose
+#  - composer --verbose --prefer-dist --no-progress --no-interaction --ansi --classmap-authoritative install
+#  - composer licenses --no-interaction --ansi --verbose
 
   # Export environment settings
-  - source ./init_env
+#  - source ./init_env
 
   # Info for debug
-  - echo $PATH
-  - ls -la /home/travis/build/GameDevBy/site/vendor/bin
-  - ls -la /home/travis/build/GameDevBy/site/node_modules/.bin
+#  - echo $PATH
+#  - ls -la /home/travis/build/GameDevBy/site/vendor/bin
+#  - ls -la /home/travis/build/GameDevBy/site/node_modules/.bin
 
   # Check npm
-  - npm audit
+#  - npm audit
 
   # Check code style
-  - composer drupal:check --no-interaction --ansi --verbose
+#  - composer drupal:check --no-interaction --ansi --verbose
 
   # Define build properties for the local test environment
   # - echo -e "drupal.base_url = http://localhost:8888\n" > build.properties.local
